# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: maxentpy
        environment-file: conda_environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: 4.10.1-5
        use-mamba: true
    - name: Test with pytest
      shell: bash -l {0}
      run: | 
        python setup.py build_ext --inplace
        pytest --verbose --doctest-modules --flake8 --cov=maxentpy maxentpy
    - name: Coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
